sudo: required
services:
  - docker

before_install:
  - docker build -t alinafembendera/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alinafembendera/react-test npm test -- --coverage

after_success:
  - docker build -t alinafembendera/multi-client ./client
  - docker build -t alinafembendera/multi-nginx ./nginx
  - docker build -t alinafembendera/multi-server ./server
  - docker build -t alinafembendera/multi-worker ./worker
#Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
#The these images and push them to docker hub
  - docker push alinafembendera/multi-client
  - docker push alinafembendera/multi-nginx
  - docker push alinafembendera/multi-server
  - docker push alinafembendera/multi-worker

